# Generated by Django 5.0.6 on 2024-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_sitecontent_alter_application_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='director',
            field=models.CharField(max_length=123, verbose_name='Генеральный директор'),
        ),
    ]
