# Generated by Django 5.0.6 on 2025-04-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_sitesetting_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Изображение о нас',
            },
        ),
        migrations.RemoveField(
            model_name='categoryvacancy',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='categoryvacancy',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='SVG'),
        ),
        migrations.AddField(
            model_name='product',
            name='bore_stroke',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Диаметр и ход поршня'),
        ),
        migrations.AddField(
            model_name='product',
            name='displacement',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_power',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Мощность двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='engine_type',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Тип двигателя'),
        ),
        migrations.AddField(
            model_name='product',
            name='make',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Размер'),
        ),
    ]
