# Generated by Django 5.0.6 on 2025-04-02 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_aboutimages_remove_categoryvacancy_title_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.industry', verbose_name='индустрия'),
        ),
    ]
